import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./layout/header";
import Footer from "./layout/footer";
import NoteHeader from "./layout/noteheader";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
title: "Create Next App",
description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
  <html lang="en">
    <body className={inter.className}>
      <div style={{display:"flex", flexDirection:"column", minHeight:"100vh"}}>
        <NoteHeader />
        <main style={{flexGrow:1}}>
          <Header />
          {children}
        </main>
        <Footer />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js" strategy="beforeInteractive"></Script>
        <Script src="https://cdn.11zon.com/js/bluebird.min.js" strategy="beforeInteractive"></Script>
        <Script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js" strategy="beforeInteractive"></Script>
        <Script src="https://cdn.11zon.com/js/jspdf.umd.min.js" strategy="beforeInteractive"></Script>
        <Script src="https://cdn.11zon.com/js/pdf/pdf.min.js" strategy="beforeInteractive"></Script>
        <Script src="https://cdn.11zon.com/js/FileSaver.min.js" strategy="beforeInteractive"></Script>
      </div>
    </body>
  </html>
  );
}